name: animated_dropdown_search_codespark
description: "Empower your app with a sophisticated dropdown widget, featuring search and highlighting."

version: 2.0.1
homepage: https://github.com/Katayath-Sai-Kiran/animated_dropdown_search_codespark

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  entry: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

screenshots:

  - description: 'Multiple Selection Dropdown - Demonstrates the functionality of selecting multiple options within the dropdown, allowing users to choose more than one item from the list.'
    path: assets/300x650-02.png
    width: 300

  - description: 'Selected Dropdown Values and Options - Displays the selected values in the dropdown along with the available options, providing a clear view of the user selections and remaining choices.'
    path: assets/300x650-03.png
    width: 300

  - description: 'Single Selection Dropdown - Showcases the single selection dropdown functionality, where users can select only one option from the list at a time.'
    path: assets/300x650-05.png
    width: 300

  - description: 'Search in Multi Select Dropdown and Highlighted Options Matched - Highlights the matched text within the options during a search in the multi-select dropdown.'
    path: assets/300x650-06.png
    width: 300

  - description: 'Selected Option Highlight in Single Select Dropdown - Highlights the selected option in the single select dropdown, providing visual feedback to the user on their selection.'
    path: assets/300x650-07.png
    width: 300

  
    


 



topics:

  - dropdownmenu
  - multiselectdropdown
  - search
  - highlighting
  - animateddropdown


  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
