name: animated_dropdown_search_codespark
description: "Empower your app with a sophisticated dropdown widget, featuring search and highlighting."

version: 0.0.9
homepage: https://github.com/Katayath-Sai-Kiran/animated_dropdown_search_codespark

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  entry: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

screenshots:
  - description: 'Home Page - The main page with the Animated Dropdown Search widget in its default state, showing the initial layout and appearance within the app.'
    path: assets/screenshot1.png
  - description: 'Focused State - The widget with the search field focused, ready for input, and the dropdown options starting to appear.'
    path: assets/screenshot2.png
  - description: 'Selected - The dropdown with an item selected, showing the selected item at the top and the rest sorted alphabetically.'
    path: assets/screenshot3.png
  - description: 'Percentage Indicator - The visual scroll percentage indicator in action, showing the user’s position within the dropdown options.'
    path: assets/screenshot4.png

topics:
  - Flutter
  - Dart
  - UI Components
  - Dropdown Menu
  - Animation
  - Search Functionality
  - Custom Widgets
  - User Interface
  - Highlighting
  - Interactive Widgets
  - Sorting


  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
