name: animated_dropdown_search_codespark
description: "Empower your app with a sophisticated dropdown widget, featuring search and highlighting."

version: 1.0.5
homepage: https://github.com/Katayath-Sai-Kiran/animated_dropdown_search_codespark

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  entry: ^1.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

screenshots:

  - description: 'Matched Highlight in Options - Highlight matched text within dropdown options, making it easier for users to find relevant selections quickly.'
    path: assets/screenshot1.png
    width: 300

  - description: 'Home - The home screen of the application, providing an overview of features and functionalities available to the user.'
    path: assets/screenshot4.png
    width: 300

  - description: 'Home Focused - The home screen with a focused state, highlighting the currently active or selected feature for better user guidance.'
    path: assets/screenshot5.png
    width: 300

  - description: 'Selected Highlighted - An option in the dropdown is selected and highlighted, providing visual feedback to the user on their selection.'
    path: assets/screenshot6.png
    width: 300

  - description: 'Scroll Percentage Indicator - A scroll percentage indicator is shown, giving users a visual cue of their current scroll position within the options list.'
    path: assets/screenshot7.png
    width: 300

  - description: 'Adaptive Options Placement - Demonstrates dropdown options appearing at the top or bottom based on the available screen space.'
    path: assets/screenshot8.png
    width: 300



topics:

  - dropdownmenu
  - animation
  - searchfunctionality
  - highlighting
  - sorting


  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
