name: Publish to pub.dev

on:
  push:
    branches:
      - master
  

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for authentication using OIDC

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'  # Specify the version of Flutter you are using

      - name: Install dependencies
        run: flutter pub get

      - name: Build the package
        run: flutter pub publish --dry-run

      - name: Publish to pub.dev
        if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
        env:
          PUB_DEV_TOKEN: ${{ secrets.PUB_DEV_TOKEN }}
        run: flutter pub publish --force
